# Generated by Django 3.2.2 on 2021-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('current_balance', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('from_account', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('amount', models.FloatField(default=0, max_length=10)),
            ],
        ),
    ]
