# Generated by Django 3.2.2 on 2021-05-13 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transectionhistory',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 13, 55, 18, 28095)),
        ),
    ]
